# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a959d098957001b0f7328471b0aed38b8bb621cc12ca87e9aa9eff8ace30cc6e5667740bcd613eacbf61e75976385370ae50b286d9d4b47c4e7b698dbf3a202d

test:
  secret_key_base: e295f8d2d1344d09c789d005a679a2493d5a3fafbabd5554c71076b0c1110a7958f63525e9311edbf6146801f27a5ba6adc81b22a5299c61b3e0c46142834db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
